name: Django Application
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7

      - name: Install dependencies
        run: |
          python3 -m pip3 install --upgrade pip
          pip3 install -r ./requirements.txt

      - name: Run database migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test
